services:
  - type: web
    name: cvoca-website
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./dist
    nodeVersion: 22
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000 